-- =============================================================
-- LINE-ASSIST-008 — Mitang LINE group <-> customer binding foundation
--
-- Owner decision: cardinality C.
--   * one LINE group MAY bind to many customers
--   * one customer MAY bind to many LINE groups
--
-- Because both sides are many, the binding cannot live as a column on either
-- table. customer_id is deliberately NOT added to public.line_bot_groups, and
-- public.customers.group_id is NOT reused: that column references the CRM
-- public.groups table and is a customer-grouping concept, not a LINE identity.
-- public.line_bot_groups is the LINE registry and is a separate namespace.
--
-- This migration establishes the durable identity contract only. It creates no
-- runtime customer command, no customer intake, and no routing behavior, and it
-- does not change any LINE operating mode (command_mode, intake_mode,
-- routing_mode). Binding rows are never inserted here.
--
-- Deliberately NOT included: is_primary, primary_customer_id,
-- default_customer_id, or any other primary/default customer marker. The Owner
-- has not decided what "มีตัง สถานะ" should answer when a LINE group has more
-- than one active customer. All active customers are preserved equally, and a
-- later customer-safe command gate decides that ambiguity.
--
-- group_type is also intentionally untouched: the existence of an active binding
-- is sufficient identity for this foundation, and customer-facing behavior is
-- gated later through explicit onboarding policy.
-- =============================================================

-- -------------------------------------------------------------
-- Binding table
-- -------------------------------------------------------------

-- No customer PII is stored here by construction: the row carries a LINE group
-- id, a customer id, and lifecycle timestamps only. No name, phone, passport,
-- alien id, visa, work permit, note, message text, sender identity, or LINE
-- message id may ever be added to this table.
create table if not exists public.line_group_customer_bindings (
  id            bigint generated by default as identity primary key,
  line_group_id text not null
                references public.line_bot_groups(group_id) on delete restrict,
  customer_id   bigint not null
                references public.customers(id) on delete restrict,
  is_active     boolean not null default true,
  linked_at     timestamptz not null default now(),
  unlinked_at   timestamptz null,
  -- Lifecycle state and its timestamp cannot disagree: an active binding has no
  -- unlink time, and an inactive binding must record when it was unlinked.
  constraint line_group_customer_bindings_state_check
    check (
      (is_active and unlinked_at is null)
      or (not is_active and unlinked_at is not null)
    )
);

comment on table public.line_group_customer_bindings is
  'Many-to-many binding between LINE groups (public.line_bot_groups) and CRM customers (public.customers). Identity only: carries no customer PII and no LINE message content.';
comment on column public.line_group_customer_bindings.line_group_id is
  'LINE registry group id; references public.line_bot_groups, never public.groups.';
comment on column public.line_group_customer_bindings.customer_id is
  'CRM customer id. Never resolved to a name or any other customer attribute in this table.';
comment on column public.line_group_customer_bindings.is_active is
  'True while the binding is in force. Unbinding flips this to false; the row is never deleted.';
comment on column public.line_group_customer_bindings.unlinked_at is
  'When the binding was unbound. Null exactly while is_active is true.';

-- At most one ACTIVE binding per (group, customer) pair. This is a partial
-- unique index, not a table constraint, so inactive history rows are exempt and
-- bind -> unbind -> rebind accumulates rows instead of colliding. Neither
-- line_group_id nor customer_id is unique on its own, which is what keeps the
-- relation many-to-many. This index is the final authority on duplicate active
-- pairs; the bind RPC defers to it rather than to a read-then-write check.
create unique index if not exists uq_line_group_customer_bindings_active_pair
  on public.line_group_customer_bindings (line_group_id, customer_id)
  where is_active;

-- Reverse-direction active lookup (customer -> groups). The partial unique index
-- above already serves the group -> customers direction on its leading column,
-- so no second index is created for it.
create index if not exists idx_line_group_customer_bindings_customer_active
  on public.line_group_customer_bindings (customer_id, line_group_id)
  where is_active;

-- -------------------------------------------------------------
-- Table ACL
-- -------------------------------------------------------------

alter table public.line_group_customer_bindings enable row level security;

-- RLS is enabled with ZERO policies, so even a role holding table privileges
-- would match no rows. Explicit revokes rather than relying on the project
-- default ACL: service_role must hold zero direct privilege on this table,
-- including SELECT. All access is through the narrow RPCs below.
revoke all on table public.line_group_customer_bindings from public;
revoke all on table public.line_group_customer_bindings from anon;
revoke all on table public.line_group_customer_bindings from authenticated;
revoke all on table public.line_group_customer_bindings from service_role;

-- Privileges on public.customers and public.line_bot_groups are deliberately
-- left exactly as they are. This migration grants and revokes nothing on either.

-- -------------------------------------------------------------
-- RPC 1 — bind
-- -------------------------------------------------------------

create or replace function public.app_bind_line_group_customer(
  p_group_id text,
  p_customer_id bigint
)
returns table (binding_id bigint, already_bound boolean)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_id bigint;
begin
  if p_group_id is null or pg_catalog.btrim(p_group_id) = '' then
    raise exception using
      errcode = '22023',
      message = 'invalid group id';
  end if;

  if p_customer_id is null then
    raise exception using
      errcode = '22023',
      message = 'invalid customer id';
  end if;

  -- The LINE group must be registered and currently active. A group the OA has
  -- left must not acquire new customer identity.
  if not exists (
    select 1
      from public.line_bot_groups g
     where g.group_id = p_group_id
  ) then
    raise exception using
      errcode = 'P0002',
      message = 'LINE group registry row not found';
  end if;

  if not exists (
    select 1
      from public.line_bot_groups g
     where g.group_id = p_group_id
       and g.is_active
  ) then
    raise exception using
      errcode = '22023',
      message = 'LINE group is not active';
  end if;

  -- The customer must exist and must not be soft-deleted. Existence and deletion
  -- are separated so a deleted customer reports why it was refused.
  if not exists (
    select 1
      from public.customers c
     where c.id = p_customer_id
  ) then
    raise exception using
      errcode = 'P0002',
      message = 'customer not found';
  end if;

  if exists (
    select 1
      from public.customers c
     where c.id = p_customer_id
       and c.deleted_at is not null
  ) then
    raise exception using
      errcode = '22023',
      message = 'customer is deleted';
  end if;

  -- Concurrency: the partial unique index arbitrates. Two sessions binding the
  -- same pair at once cannot both insert -- one inserts, the other takes the
  -- DO NOTHING path and reads the winner below. No advisory lock is needed and
  -- no read-then-write race window exists.
  insert into public.line_group_customer_bindings (line_group_id, customer_id)
  values (p_group_id, p_customer_id)
  on conflict (line_group_id, customer_id) where is_active do nothing
  returning id into v_id;

  if v_id is not null then
    binding_id := v_id;
    already_bound := false;
    return next;
    return;
  end if;

  -- An active binding already existed: idempotent success, same binding id.
  select b.id
    into v_id
    from public.line_group_customer_bindings b
   where b.line_group_id = p_group_id
     and b.customer_id = p_customer_id
     and b.is_active;

  -- Defensive only. The conflicting row is committed by the time DO NOTHING
  -- returns, so this is unreachable under READ COMMITTED; if the pair somehow
  -- vanished, fail rather than report a binding that does not exist.
  if v_id is null then
    raise exception using
      errcode = '40001',
      message = 'concurrent binding change; retry';
  end if;

  binding_id := v_id;
  already_bound := true;
  return next;
end;
$$;

comment on function public.app_bind_line_group_customer(text, bigint) is
  'Binds a LINE group to a customer, idempotently. Requires an active LINE group and a customer that is not soft-deleted. Returns the binding id and whether an active binding already existed. Returns no customer PII and changes no LINE operating mode.';

revoke all on function public.app_bind_line_group_customer(text, bigint) from public;
revoke all on function public.app_bind_line_group_customer(text, bigint) from anon;
revoke all on function public.app_bind_line_group_customer(text, bigint) from authenticated;
grant execute on function public.app_bind_line_group_customer(text, bigint) to service_role;

-- -------------------------------------------------------------
-- RPC 2 — unbind
-- -------------------------------------------------------------

create or replace function public.app_unbind_line_group_customer(
  p_group_id text,
  p_customer_id bigint
)
returns table (binding_id bigint, unbound boolean)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_id bigint;
begin
  if p_group_id is null or pg_catalog.btrim(p_group_id) = '' then
    raise exception using
      errcode = '22023',
      message = 'invalid group id';
  end if;

  if p_customer_id is null then
    raise exception using
      errcode = '22023',
      message = 'invalid customer id';
  end if;

  -- Deliberately no is_active check on the LINE group and no deleted_at check on
  -- the customer: withdrawing identity must stay possible after either side has
  -- been deactivated or soft-deleted. Binding rows are never deleted, only
  -- deactivated, so history survives permanently.
  update public.line_group_customer_bindings b
     set is_active = false,
         unlinked_at = pg_catalog.now()
   where b.line_group_id = p_group_id
     and b.customer_id = p_customer_id
     and b.is_active
  returning b.id into v_id;

  if v_id is not null then
    binding_id := v_id;
    unbound := true;
    return next;
    return;
  end if;

  -- Nothing active to unbind. Report the most recent historical row when the
  -- pair was bound before, so a repeated unbind is idempotent rather than an
  -- error, and null when the pair was never bound at all.
  select b.id
    into v_id
    from public.line_group_customer_bindings b
   where b.line_group_id = p_group_id
     and b.customer_id = p_customer_id
   order by b.linked_at desc, b.id desc
   limit 1;

  binding_id := v_id;
  unbound := false;
  return next;
end;
$$;

comment on function public.app_unbind_line_group_customer(text, bigint) is
  'Deactivates the active binding between a LINE group and a customer. Never deletes a row, so binding history is permanent. Idempotent, and still permitted when the LINE group is inactive or the customer is soft-deleted.';

revoke all on function public.app_unbind_line_group_customer(text, bigint) from public;
revoke all on function public.app_unbind_line_group_customer(text, bigint) from anon;
revoke all on function public.app_unbind_line_group_customer(text, bigint) from authenticated;
grant execute on function public.app_unbind_line_group_customer(text, bigint) to service_role;

-- -------------------------------------------------------------
-- RPC 3 — runtime active customer ids
-- -------------------------------------------------------------

-- Identity resolution only. This returns customer ids and nothing else: no name,
-- phone, document, fee, case or status data, and no binding history. It also
-- makes no choice among multiple customers -- ordering is by customer_id purely
-- for determinism and carries no precedence meaning. Deciding which customer a
-- customer-safe command should answer for is a later Owner gate.
create or replace function public.app_list_line_group_customer_ids(
  p_group_id text
)
returns table (customer_id bigint)
language sql
stable
security definer
set search_path = ''
as $$
  select b.customer_id
    from public.line_group_customer_bindings b
    join public.customers c
      on c.id = b.customer_id
    join public.line_bot_groups g
      on g.group_id = b.line_group_id
   where b.line_group_id = p_group_id
     and b.is_active
     and c.deleted_at is null
     and g.is_active
   order by b.customer_id;
$$;

comment on function public.app_list_line_group_customer_ids(text) is
  'Returns the customer ids actively bound to a LINE group, excluding soft-deleted customers and inactive LINE groups, ordered by customer id. Identity resolution only: no customer PII, no binding history, and no precedence among multiple customers.';

revoke all on function public.app_list_line_group_customer_ids(text) from public;
revoke all on function public.app_list_line_group_customer_ids(text) from anon;
revoke all on function public.app_list_line_group_customer_ids(text) from authenticated;
grant execute on function public.app_list_line_group_customer_ids(text) to service_role;
