-- =============================================================
-- LINE-ASSIST-009 — Mitang internal price catalog foundation (Pricing V1)
--
-- Authoritative, deterministic price lookup for INTERNAL employee/work groups.
-- There is no AI, no NLU, no n8n and no external call anywhere in this path: a
-- query is normalized, matched against a seeded alias table by longest literal
-- alias, and answered from seeded catalog rows.
--
-- Scope model
-- -----------
--   scope='global'  -> country_code IS NULL, applies to every nationality
--   scope='country' -> country_code IS NOT NULL (only 'LA' is seeded in V1)
-- Adding Myanmar ('MM') or Cambodia ('KH') later needs new rows only; no schema
-- change. They are deliberately NOT seeded here.
--
-- Cost model
-- ----------
-- Costs live in a child table, never in prose, so lookup stays deterministic:
--   * ordinary service        -> exactly one cost row, location_key IS NULL
--   * แจ้งเข้า (แจ้งออกตาย)  -> three cost rows, one per province
--   * ขึ้นทะเบียนใหม่         -> ZERO cost rows and cost_status='unknown'
-- cost_status='unknown' can therefore never surface a fabricated number: there
-- is no row to read, and the lookup returns a null cost with the status intact.
--
-- This migration adds pricing tables, one immutable normalizer and one narrow
-- read RPC. It touches no existing table, no customer data, no LINE operating
-- mode, no router, no scheduler and no Edge Function.
--
-- Fail-closed
-- -----------
-- This is a first-time foundation, so it refuses to run against unexpected prior
-- state instead of absorbing it. The preflight below aborts if any intended
-- pricing object already exists, every CREATE is a plain CREATE rather than
-- IF NOT EXISTS or OR REPLACE, and the seeds carry no ON CONFLICT clause: a seed
-- that cannot be inserted exactly is an error. Nothing here inspects, drops,
-- reconciles or repairs anything outside the pricing objects it creates.
-- =============================================================

-- -------------------------------------------------------------
-- Preflight — abort on any pre-existing pricing object
-- -------------------------------------------------------------

do $preflight$
declare
  v_existing text;
begin
  select pg_catalog.string_agg(t.obj, ', ' order by t.obj)
    into v_existing
    from (
      select 'table public.line_price_services' as obj
       where pg_catalog.to_regclass('public.line_price_services') is not null
      union all
      select 'table public.line_price_service_costs'
       where pg_catalog.to_regclass('public.line_price_service_costs') is not null
      union all
      select 'table public.line_price_service_aliases'
       where pg_catalog.to_regclass('public.line_price_service_aliases') is not null
      union all
      select 'function public.line_price_normalize(text)'
       where pg_catalog.to_regprocedure('public.line_price_normalize(text)') is not null
      union all
      select 'function public.app_lookup_line_price(text)'
       where pg_catalog.to_regprocedure('public.app_lookup_line_price(text)') is not null
    ) as t;

  -- Deliberately reports every conflicting object at once and changes none of
  -- them. Reconciliation is an Owner decision, not a migration side effect.
  if v_existing is not null then
    raise exception using
      errcode = '42710',
      message = 'pricing foundation preflight failed: already present: ' || v_existing,
      hint = 'This migration builds the pricing foundation from scratch. Investigate the existing objects; do not drop or reconcile them here.';
  end if;
end
$preflight$;

-- -------------------------------------------------------------
-- Query normalizer
-- -------------------------------------------------------------

-- Folds case and strips everything that is not a digit, a latin letter or a Thai
-- character, so spacing, punctuation and dashes cannot change a match. Written
-- as IMMUTABLE so stored aliases can be constrained to already-normal form.
-- '45-60 วัน' and '45–60วัน' both normalize to '4560วัน'.
create function public.line_price_normalize(p_text text)
returns text
language sql
immutable
set search_path = ''
as $$
  select coalesce(
    pg_catalog.regexp_replace(pg_catalog.lower(p_text), '[^0-9a-zก-๙]', '', 'g'),
    ''
  );
$$;

comment on function public.line_price_normalize(text) is
  'Deterministic price-query normalizer: lowercases and removes every character that is not a digit, latin letter or Thai character. Immutable so alias rows can be constrained to normal form.';

-- -------------------------------------------------------------
-- Catalog
-- -------------------------------------------------------------

create table public.line_price_services (
  id              bigint generated by default as identity primary key,
  service_key     text not null unique,
  service_name    text not null,
  variant_name    text null,
  scope           text not null,
  country_code    text null,
  country_name    text null,
  sale_price_min  numeric(12,2) not null,
  sale_price_max  numeric(12,2) not null,
  cost_status     text not null,
  note            text null,
  is_active       boolean not null default true,
  sort_order      integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint line_price_services_scope_check
    check (scope in ('global', 'country')),
  constraint line_price_services_cost_status_check
    check (cost_status in ('confirmed', 'unknown')),
  -- A global row must carry no country at all; a country row must carry both the
  -- code and its display name. This is what keeps 'global' unambiguous.
  constraint line_price_services_country_scope_check
    check (
      (scope = 'global' and country_code is null and country_name is null)
      or (scope = 'country' and country_code is not null and country_name is not null)
    ),
  constraint line_price_services_country_code_check
    check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  constraint line_price_services_sale_range_check
    check (sale_price_min >= 0 and sale_price_max >= sale_price_min)
);

comment on table public.line_price_services is
  'Internal Mitang price catalog. Sale range is authoritative here; confirmed costs live in line_price_service_costs. Contains no customer data.';
comment on column public.line_price_services.cost_status is
  'confirmed = at least one cost row exists; unknown = cost is not confirmed and NO cost row exists, so no number can be fabricated.';
comment on column public.line_price_services.variant_name is
  'Human-readable variant qualifier such as a turnaround window; null when the service has no variant.';

create index idx_line_price_services_active
  on public.line_price_services (sort_order, id)
  where is_active;

-- -------------------------------------------------------------
-- Costs (child)
-- -------------------------------------------------------------

create table public.line_price_service_costs (
  id                   bigint generated by default as identity primary key,
  service_id           bigint not null
                       references public.line_price_services(id) on delete cascade,
  location_key         text null,
  location_name        text null,
  location_match_norms text[] not null default '{}',
  cost_amount          numeric(12,2) not null,
  sort_order           integer not null default 0,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  constraint line_price_service_costs_amount_check
    check (cost_amount >= 0),
  -- Either this is the service's single cost (no location at all), or it is a
  -- location variant and must carry a key, a display name and at least one
  -- normalized match token. Half-populated location rows cannot exist.
  constraint line_price_service_costs_location_check
    check (
      (location_key is null
        and location_name is null
        and pg_catalog.cardinality(location_match_norms) = 0)
      or (location_key is not null
        and location_name is not null
        and pg_catalog.cardinality(location_match_norms) >= 1)
    )
);

comment on table public.line_price_service_costs is
  'Confirmed internal cost rows. A service either has one location-free cost row, or several location-specific rows. A service with cost_status=unknown has none.';
comment on column public.line_price_service_costs.location_match_norms is
  'Normalized tokens that select this location variant when they appear in a query, e.g. {กทม,กรุงเทพ}. Matching is literal containment only.';

-- One location-free cost per service.
create unique index uq_line_price_service_costs_single
  on public.line_price_service_costs (service_id)
  where location_key is null;

-- One cost per (service, location) for location-specific services.
create unique index uq_line_price_service_costs_location
  on public.line_price_service_costs (service_id, location_key)
  where location_key is not null;

create index idx_line_price_service_costs_service
  on public.line_price_service_costs (service_id, sort_order, id);

-- -------------------------------------------------------------
-- Aliases
-- -------------------------------------------------------------

-- Deterministic lookup keys. Several catalog rows MAY share one generic alias on
-- purpose: 'พาสลาว' is attached to both Laos passport variants so a generic
-- question returns both, while the longer 'พาสลาวด่วน' is attached only to the
-- express row. Because the RPC keeps only the longest matching alias, a more
-- specific alias always beats the generic one without any ranking column.
create table public.line_price_service_aliases (
  id         bigint generated by default as identity primary key,
  service_id bigint not null
             references public.line_price_services(id) on delete cascade,
  alias_norm text not null,
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  constraint line_price_service_aliases_norm_check
    check (alias_norm <> '' and alias_norm = public.line_price_normalize(alias_norm))
);

comment on table public.line_price_service_aliases is
  'Normalized lookup aliases. alias_norm is constrained to already-normal form so a query normalized the same way can be matched by literal containment.';

create unique index uq_line_price_service_aliases_pair
  on public.line_price_service_aliases (alias_norm, service_id);

create index idx_line_price_service_aliases_norm
  on public.line_price_service_aliases (alias_norm)
  where is_active;

-- -------------------------------------------------------------
-- Table ACL
-- -------------------------------------------------------------

-- RLS on with ZERO policies on all three tables, and zero direct privilege for
-- every role including service_role. Cost data is internal, so the only way to
-- read it is the SECURITY DEFINER RPC below, whose output is bounded to pricing
-- facts.
alter table public.line_price_services enable row level security;
alter table public.line_price_service_costs enable row level security;
alter table public.line_price_service_aliases enable row level security;

revoke all on table public.line_price_services from public;
revoke all on table public.line_price_services from anon;
revoke all on table public.line_price_services from authenticated;
revoke all on table public.line_price_services from service_role;

revoke all on table public.line_price_service_costs from public;
revoke all on table public.line_price_service_costs from anon;
revoke all on table public.line_price_service_costs from authenticated;
revoke all on table public.line_price_service_costs from service_role;

revoke all on table public.line_price_service_aliases from public;
revoke all on table public.line_price_service_aliases from anon;
revoke all on table public.line_price_service_aliases from authenticated;
revoke all on table public.line_price_service_aliases from service_role;

revoke all on function public.line_price_normalize(text) from public;
revoke all on function public.line_price_normalize(text) from anon;
revoke all on function public.line_price_normalize(text) from authenticated;
revoke all on function public.line_price_normalize(text) from service_role;

-- -------------------------------------------------------------
-- Seed — exactly 12 catalog entries (8 global, 4 Laos)
-- -------------------------------------------------------------

-- Sale prices stated as a single figure in the source are seeded with
-- min = max. No cost is invented: GLOBAL-07 is seeded cost_status='unknown'.
insert into public.line_price_services (
  service_key, service_name, variant_name, scope, country_code, country_name,
  sale_price_min, sale_price_max, cost_status, note, sort_order
) values
  ('global-01', 'แจ้งเข้า', null, 'global', null, null, 2500, 2500, 'confirmed', null, 10),
  ('global-02', 'แจ้งเข้า (แจ้งออกตาย)', null, 'global', null, null, 3500, 4500, 'confirmed', null, 20),
  ('global-03', 'แจ้งออก', null, 'global', null, null, 500, 500, 'confirmed', null, 30),
  ('global-04', 'รายงานตัว 90 วัน ไม่ปรับ', null, 'global', null, null, 200, 200, 'confirmed', null, 40),
  ('global-05', 'รายงานตัว 90 วัน ปรับ', null, 'global', null, null, 700, 800, 'confirmed', null, 50),
  ('global-06', 'ตีวีซ่า', null, 'global', null, null, 2000, 2000, 'confirmed', null, 60),
  ('global-07', 'ขึ้นทะเบียนใหม่', null, 'global', null, null, 6500, 8500, 'unknown', null, 70),
  ('global-08', 'ต่ออายุ มติ 11', null, 'global', null, null, 5500, 7500, 'confirmed', 'มีประกัน ลดได้ / ไม่เอาวีซ่า 5500', 80),
  ('la-01', 'MOU ลาว', null, 'country', 'LA', 'ลาว', 15000, 17000, 'confirmed', null, 110),
  ('la-02', 'ต่ออายุ MOU ลาว', null, 'country', 'LA', 'ลาว', 6500, 8500, 'confirmed', null, 120),
  ('la-03', 'Passport ลาว ปกติ', '45–60 วัน', 'country', 'LA', 'ลาว', 6000, 6500, 'confirmed', null, 130),
  ('la-04', 'Passport ลาว ด่วนพิเศษ', '15–20 วัน', 'country', 'LA', 'ลาว', 7000, 7500, 'confirmed', null, 140);

-- Location-free confirmed costs. GLOBAL-02 is intentionally absent here and
-- GLOBAL-07 is intentionally absent everywhere.
insert into public.line_price_service_costs (service_id, cost_amount, sort_order)
select s.id, v.cost_amount, 0
  from (values
    ('global-01', 410::numeric),
    ('global-03', 0::numeric),
    ('global-04', 80::numeric),
    ('global-05', 200::numeric),
    ('global-06', 1200::numeric),
    ('global-08', 4300::numeric),
    ('la-01', 9600::numeric),
    ('la-02', 4100::numeric),
    ('la-03', 5000::numeric),
    ('la-04', 6500::numeric)
  ) as v(service_key, cost_amount)
  join public.line_price_services s on s.service_key = v.service_key;

-- GLOBAL-02 province-specific costs. Kept as separate rows so a query naming a
-- province resolves to exactly one number, and a query naming none returns all
-- three rather than the router guessing.
insert into public.line_price_service_costs (
  service_id, location_key, location_name, location_match_norms, cost_amount, sort_order
)
select s.id, v.location_key, v.location_name, v.location_match_norms, v.cost_amount, v.sort_order
  from (values
    ('global-02', 'pathum',     'ปทุมธานี',  array['ปทุม'],            860::numeric,  1),
    ('global-02', 'bangkok',    'กรุงเทพฯ',  array['กทม','กรุงเทพ'],  2510::numeric,  2),
    ('global-02', 'nonthaburi', 'นนทบุรี',   array['นนทบุรี','นนท'],  1460::numeric,  3)
  ) as v(service_key, location_key, location_name, location_match_norms, cost_amount, sort_order)
  join public.line_price_services s on s.service_key = v.service_key;

-- Aliases. Generic aliases are attached to every variant they legitimately mean;
-- specific aliases are longer, so longest-match resolves the ambiguity.
insert into public.line_price_service_aliases (service_id, alias_norm)
select s.id, v.alias_norm
  from (values
    ('global-01', 'แจ้งเข้า'),
    ('global-02', 'แจ้งเข้าแจ้งออกตาย'),
    ('global-02', 'แจ้งออกตาย'),
    ('global-03', 'แจ้งออก'),
    ('global-04', 'รายงานตัว'),
    ('global-04', 'รายงานตัวไม่ปรับ'),
    ('global-04', 'รายงานตัว90วันไม่ปรับ'),
    ('global-04', '90วันไม่ปรับ'),
    ('global-05', 'รายงานตัว'),
    ('global-05', 'รายงานตัวปรับ'),
    ('global-05', 'รายงานตัว90วันปรับ'),
    ('global-05', '90วันปรับ'),
    ('global-06', 'ตีวีซ่า'),
    ('global-07', 'ขึ้นทะเบียน'),
    ('global-07', 'ขึ้นทะเบียนใหม่'),
    ('global-08', 'มติ11'),
    ('global-08', 'ต่ออายุมติ11'),
    ('la-01', 'mouลาว'),
    -- Renewal is seeded in both word orders. LA-01 carries only the bare
    -- 'mouลาว' (6 chars), so every renewal alias below is strictly longer and
    -- wins outright: "MOU ลาว ต่ออายุ" can never fall back to the new-MOU row.
    ('la-02', 'ต่อmouลาว'),
    ('la-02', 'ต่ออายุmouลาว'),
    ('la-02', 'mouลาวต่อ'),
    ('la-02', 'mouลาวต่ออายุ'),
    ('la-03', 'พาสลาว'),
    ('la-03', 'พาสปอร์ตลาว'),
    ('la-03', 'passportลาว'),
    ('la-03', 'พาสลาวปกติ'),
    ('la-03', 'พาสปอร์ตลาวปกติ'),
    ('la-03', 'พาสลาว4560วัน'),
    ('la-03', 'พาสปอร์ตลาว4560วัน'),
    ('la-04', 'พาสลาว'),
    ('la-04', 'พาสปอร์ตลาว'),
    ('la-04', 'passportลาว'),
    ('la-04', 'พาสลาวด่วน'),
    ('la-04', 'พาสปอร์ตลาวด่วน'),
    ('la-04', 'พาสลาวด่วนพิเศษ'),
    ('la-04', 'พาสปอร์ตลาวด่วนพิเศษ'),
    ('la-04', 'พาสลาว1520วัน'),
    ('la-04', 'พาสปอร์ตลาว1520วัน')
  ) as v(service_key, alias_norm)
  join public.line_price_services s on s.service_key = v.service_key;

-- -------------------------------------------------------------
-- Lookup RPC
-- -------------------------------------------------------------

-- One row per (service, cost). A service with no cost row still returns exactly
-- one row carrying a null cost and cost_status='unknown', so the caller can say
-- "ยังไม่ยืนยัน" without inventing a figure. No customer, case, document or
-- registry data is reachable from here.
create function public.app_lookup_line_price(p_query text)
returns table (
  service_key     text,
  service_name    text,
  variant_name    text,
  scope           text,
  country_code    text,
  cost_status     text,
  location_name   text,
  cost_amount     numeric,
  sale_price_min  numeric,
  sale_price_max  numeric,
  note            text
)
language sql
stable
security definer
set search_path = ''
as $$
  with q as (
    select public.line_price_normalize(p_query) as norm
  ),
  hit as (
    -- Every alias literally contained in the normalized query.
    select a.service_id,
           pg_catalog.length(a.alias_norm) as alias_len
      from public.line_price_service_aliases a
     cross join q
     where a.is_active
       and q.norm <> ''
       and pg_catalog.strpos(q.norm, a.alias_norm) > 0
  ),
  matched as (
    -- Keep only the longest alias. Ties are intentional: a generic alias shared
    -- by several variants returns all of them.
    select distinct h.service_id
      from hit h
     where h.alias_len = (select pg_catalog.max(h2.alias_len) from hit h2)
  ),
  svc as (
    select s.*
      from public.line_price_services s
      join matched m on m.service_id = s.id
     where s.is_active
  ),
  loc as (
    -- Location variants this query explicitly names.
    select c.id as cost_id, c.service_id
      from public.line_price_service_costs c
     cross join q
     where c.location_key is not null
       and exists (
         select 1
           from pg_catalog.unnest(c.location_match_norms) as t(token)
          where pg_catalog.strpos(q.norm, t.token) > 0
       )
  )
  select s.service_key,
         s.service_name,
         s.variant_name,
         s.scope,
         s.country_code,
         s.cost_status,
         c.location_name,
         c.cost_amount,
         s.sale_price_min,
         s.sale_price_max,
         s.note
    from svc s
    left join public.line_price_service_costs c
      on c.service_id = s.id
   where c.id is null
      -- No province named: return every cost variant, never guess one.
      or not exists (select 1 from loc l where l.service_id = s.id)
      -- Province named: return only the variants it names.
      or exists (select 1 from loc l where l.cost_id = c.id)
   order by s.sort_order, s.id, c.sort_order nulls first, c.id;
$$;

comment on function public.app_lookup_line_price(text) is
  'Deterministic internal price lookup. Normalizes the query, keeps the longest matching alias, and returns one row per matching service and cost. Returns zero rows when nothing matches. Exposes pricing facts only: no customer, case, document or LINE registry data, and no AI or external call.';

revoke all on function public.app_lookup_line_price(text) from public;
revoke all on function public.app_lookup_line_price(text) from anon;
revoke all on function public.app_lookup_line_price(text) from authenticated;
grant execute on function public.app_lookup_line_price(text) to service_role;
